// <auto-generated />
namespace Microsoft.Extensions.Configuration.Xml
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    public static class Resources
    {
        private static readonly ResourceManager _resourceManager = ConfigXmlSR.ResourceManager;

        /// <summary>
        /// File path must be a non-empty string.
        /// </summary>
        public static string Error_InvalidFilePath
        {
            get => ConfigXmlSR.ResourceManager.GetString("Error_InvalidFilePath");
        }

        /// <summary>
        /// File path must be a non-empty string.
        /// </summary>
        public static string FormatError_InvalidFilePath()
            => ConfigXmlSR.ResourceManager.GetString("Error_InvalidFilePath");

        /// <summary>
        /// A duplicate key '{0}' was found.{1}
        /// </summary>
        public static string Error_KeyIsDuplicated
        {
            get => ConfigXmlSR.ResourceManager.GetString("Error_KeyIsDuplicated");
        }

        /// <summary>
        /// A duplicate key '{0}' was found.{1}
        /// </summary>
        public static string FormatError_KeyIsDuplicated(object p0, object p1)
            => string.Format(CultureInfo.CurrentCulture, ConfigXmlSR.ResourceManager.GetString("Error_KeyIsDuplicated"), p0, p1);

        /// <summary>
        /// XML namespaces are not supported.{0}
        /// </summary>
        public static string Error_NamespaceIsNotSupported
        {
            get => ConfigXmlSR.ResourceManager.GetString("Error_NamespaceIsNotSupported");
        }

        /// <summary>
        /// XML namespaces are not supported.{0}
        /// </summary>
        public static string FormatError_NamespaceIsNotSupported(object p0)
            => string.Format(CultureInfo.CurrentCulture, ConfigXmlSR.ResourceManager.GetString("Error_NamespaceIsNotSupported"), p0);

        /// <summary>
        /// Unsupported node type '{0}' was found.{1}
        /// </summary>
        public static string Error_UnsupportedNodeType
        {
            get => ConfigXmlSR.ResourceManager.GetString("Error_UnsupportedNodeType");
        }

        /// <summary>
        /// Unsupported node type '{0}' was found.{1}
        /// </summary>
        public static string FormatError_UnsupportedNodeType(object p0, object p1)
            => string.Format(CultureInfo.CurrentCulture, ConfigXmlSR.ResourceManager.GetString("Error_UnsupportedNodeType"), p0, p1);

        /// <summary>
        ///  Line {0}, position {1}.
        /// </summary>
        public static string Msg_LineInfo
        {
            get => ConfigXmlSR.ResourceManager.GetString("Msg_LineInfo");
        }

        /// <summary>
        ///  Line {0}, position {1}.
        /// </summary>
        public static string FormatMsg_LineInfo(object p0, object p1)
            => string.Format(CultureInfo.CurrentCulture, ConfigXmlSR.ResourceManager.GetString("Msg_LineInfo"), p0, p1);

    }
}
