// <auto-generated />
namespace Microsoft.Extensions.Configuration
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    public static class Resources
    {
        private static readonly ResourceManager _resourceManager = ConfigSR.ResourceManager;

        /// <summary>
        /// A configuration source is not registered. Please register one before setting a value.
        /// </summary>
        internal static string Error_NoSources
        {
            get => Microsoft.Extensions.Configuration.ConfigSR.ResourceManager.GetString("Error_NoSources");
        }

        /// <summary>
        /// A configuration source is not registered. Please register one before setting a value.
        /// </summary>
        internal static string FormatError_NoSources()
            => Microsoft.Extensions.Configuration.ConfigSR.ResourceManager.GetString("Error_NoSources");

    }
}
