// <auto-generated />
namespace Microsoft.Extensions.Configuration.Ini
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    public static class Resources
    {
        private static readonly ResourceManager _resourceManager = ConfigIniSR.ResourceManager;

        /// <summary>
        /// File path must be a non-empty string.
        /// </summary>
        internal static string Error_InvalidFilePath
        {
            get => ConfigIniSR.ResourceManager.GetString("Error_InvalidFilePath");
        }

        /// <summary>
        /// File path must be a non-empty string.
        /// </summary>
        internal static string FormatError_InvalidFilePath()
            => ConfigSR.ResourceManager.GetString("Error_InvalidFilePath");

        /// <summary>
        /// A duplicate key '{0}' was found.
        /// </summary>
        internal static string Error_KeyIsDuplicated
        {
            get => ConfigIniSR.ResourceManager.GetString("Error_KeyIsDuplicated");
        }

        /// <summary>
        /// A duplicate key '{0}' was found.
        /// </summary>
        internal static string FormatError_KeyIsDuplicated(object p0)
            => string.Format(CultureInfo.CurrentCulture, ConfigSR.ResourceManager.GetString("Error_KeyIsDuplicated"), p0);

        /// <summary>
        /// Unrecognized line format: '{0}'.
        /// </summary>
        internal static string Error_UnrecognizedLineFormat
        {
            get => ConfigSR.ResourceManager.GetString("Error_UnrecognizedLineFormat");
        }

        /// <summary>
        /// Unrecognized line format: '{0}'.
        /// </summary>
        internal static string FormatError_UnrecognizedLineFormat(object p0)
            => string.Format(CultureInfo.CurrentCulture, ConfigSR.ResourceManager.GetString("Error_UnrecognizedLineFormat"), p0);

    }
}
